# Generated by Django 4.1.2 on 2023-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portas',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Código')),
                ('Nome', models.CharField(max_length=50, verbose_name='Nome da Porta')),
                ('Descricao', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descrição da Porta')),
            ],
            options={
                'db_table': 'Portas',
            },
        ),
    ]
