# Generated by Django 4.1.2 on 2023-05-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HardwareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placas',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Código')),
                ('Nome', models.CharField(max_length=50, verbose_name='Nome da Placa')),
                ('Descricao', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descrição da Placa')),
                ('Porta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placas_portas', to='HardwareApp.portas')),
            ],
            options={
                'db_table': 'Placas',
            },
        ),
    ]
